compatibility_flags = ["nodejs_compat"]
name = "actor-table"
main = "actors/index.ts"
compatibility_date = "2024-11-27"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "ACTOR_DO"
class_name = "ActorDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ActorDurableObject"]
